[tools]
terraform = "1.9.1"
python = "3.12.2"
go = "1.22.2"
usage = "latest"
deno = "latest"
yarn = "latest"
node = "latest"
ruby = "3.3.6"

[settings]
legacy_version_file_disable_tools = ["terraform"]
